global proc jiancha()
{ 
    if (`window -ex jianchaWin`)
       deleteUI jianchaWin;
       window  -t "检查╮(╯▽╰)╭" -wh 260 230 jianchaWin;
       rowColumnLayout;
       text -bgc 0.2 0.5 0.7 -l "注意检查人物文件之前一定要保存";
       textScrollList -ams 1 cuowuxianshi;
       button -l "检查本文件隐藏组(不推荐人物使用)" -c "zhixingjiancha";
       //button -l "删除Dyn上传CH也可以CH整理" -c "DYNqingchu";
       //button -l "动画曲线动作A" -c "DonghuanquxianA";
       //button -l "动画曲线动作B" -c "DonghuanquxianB";
       //button -l "脸部表情曲线动作" -c "LIanBuDongBu";
       //button -l "添加简模切换插件" -c "jianmoguanlian";
       window -e -wh 260 230 jianchaWin;
       showWindow jianchaWin;
}
global proc zhixingjiancha()
{
   string $ingfewaA[]=`ls -typ "transform"`;
int $zhengheShuA=size($ingfewaA);
for ($qw=0;$qw<$zhengheShuA;$qw++)
{
    string $cccccA=`getAttr ($ingfewaA[$qw]+".v")`;
    int $qxs=0;
if ($qxs=$cccccA)
 {   
     print ($ingfewaA[$qw]+"该物体显示没有问题,共"+$zhengheShuA+"个物体;\n");

 }
else
 {
    select -tgl $ingfewaA[$qw] ;
    select -d persp ;
select -d top ;
select -d front ;
select -d side ;
 }
}
string $xuanzhexianshi[]=`ls -sl`;
for ($xianshide in $xuanzhexianshi)
{
textScrollList  -e -append $xianshide -sc xuanzedaihaoB  cuowuxianshi;

} 
select -cl  ;
}
global proc xuanzedaihaoB()
{
    string $xuanzelitouwuti[]=`textScrollList -q -si cuowuxianshi`;
    select -r $xuanzelitouwuti;
}
jiancha;